### ISSUE TITLE
Not scraping all applications

### ISSUE THREAD

**Issue by CloCkWeRX** [planningalerts-scrapers/penrith#3]
Address: 18 Twin Creeks Drive LUDDENHAM NSW 2745 is the latest one we have, ~16 days ago - but applications on exhibition show at least 7 others since then.

**Comment by CloCkWeRX** [comment]
Fixed in 0d5b29d2

Manually ran revision 0d5b29d2 and completed successfully less than a minute ago.
run time 35 s
82 records added in the database
4 pages scraped

**Comment by henare** [comment]
Splendid :tada:
